# Generated by Django 4.1.3 on 2022-11-15 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 15, 13, 40, 37, 469123, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
